# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kyle Simmons
email:

#write html inside the double quotes to display in jumbotron
description: "<h1>Cyber stuff</h1><h2>&#92;x48&#92;x65&#92;x6c&#92;x6c&#92;x6f &#92;x57&#92;x6f&#92;x72&#92;x6c&#92;x64</h2>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:  kyle-c-simmons

# Build settings
markdown: kramdown
